### ISSUE TITLE
Update readme with missing commands

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/dev-pro-tips-bot#21]
Readme is missing commands:

`!roll`
`!choose`
`!docs`

Owner commands:

`!roles`
`!add_confirm`

Owner context menu commands:

`giveaway`

**Comment by Jbyford89** [comment]
**_Does this need to be assigned or can I just do a PR and correct the issue? Is there a PR template you use?_**

**Comment by DenverCoder1** [comment]
Feel free to open a PR :+1:

**Comment by DenverCoder1** [comment]
Fixed by #40
