### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/dev-pro-tips-bot#43]
Currently the messages sent to the user are uninformative.

When the error can be identified, instead of just logging the error in a separate channel, the error message should be more specific.

eg:

"Command not found" instead of:

![image](https://user-images.githubusercontent.com/20955511/163648509-ce802a36-2493-4b8f-bda0-6bd220958791.png)

"Missing required argument" instead of:

![image](https://user-images.githubusercontent.com/20955511/163648555-ba26c181-ad85-45ed-a5d2-0acf53ab52ab.png)

**Comment by Vyvy-vi** [comment]
I'd like to work on this.

**Comment by DenverCoder1** [comment]
Thanks, that would be great!
